### ISSUE TITLE
Horizontal Stack Layout Issues

### ISSUE THREAD

**Issue by ColdstarJoey** [ameerthehacker/XamarinFormValidationDemo#1]
Hi I have used your code to create entry messages but when the entry is in a stack layout which is set to horizontal then the error message shows on the right side, do you know what to fix this so it still appears under control @ameerthehacker ??

**Comment by ameerthehacker** [comment]
Hi @Joeeyirelandd, a simple fix would be to put each individual entry into a separate stack layout with its orientation set to vertical

**Comment by ColdstarJoey** [comment]
@ameerthehacker I have sections going across so for example, in each stack layout there is a label, picker and an entry so to keep with design I need them all in there as they go across the screen.

**Comment by ColdstarJoey** [comment]
For example 

`
            <StackLayout Orientation="Horizontal" HorizontalOptions="Fill">
                <Label x:Name="tyreLabel" Text="Tyres (and spare)" FontSize="Default" WidthRequest="180" Margin="10,10,10,10" HorizontalTextAlignment="Start" ></Label>
                <Picker x:Name="tyrePicker" Title="Select Condition" Margin="0,0,30,0" HorizontalOptions="Center">
                    <Picker.ItemsSource>
                        <x:Array Type="{x:Type x:String}">
                            <x:String>Yes</x:String>
                            <x:String>No</x:String>
                            <x:String>N/A</x:String>
                        </x:Array>
                    </Picker.ItemsSource>
                </Picker>
                <Entry x:Name="tyreComments" FontSize="Default" WidthRequest="180" HorizontalTextAlignment="Start">
                    <Entry.Behaviors>
                        <Behaviors:ValidationBehavior PropertyName="Text">
                            <Behaviors:ValidationBehavior.Validators>
                                <Validators:RequiredValidator />
                                <Validators:FormatValidator
                            Message="" 
                            Format="" />
                            </Behaviors:ValidationBehavior.Validators>
                        </Behaviors:ValidationBehavior>
                    </Entry.Behaviors>
                </Entry>
            </StackLayout>`

**Comment by ameerthehacker** [comment]
<StackLayout Orientation="Horizontal" HorizontalOptions="Fill"> <Label x:Name="tyreLabel" Text="Tyres (and spare)" FontSize="Default" WidthRequest="180" Margin="10,10,10,10" HorizontalTextAlignment="Start" ></Label> <Picker x:Name="tyrePicker" Title="Select Condition" Margin="0,0,30,0" HorizontalOptions="Center"> <Picker.ItemsSource> <x:Array Type="{x:Type x:String}"> <x:String>Yes</x:String> <x:String>No</x:String> <x:String>N/A</x:String> </x:Array> </Picker.ItemsSource> </Picker> <StackLayout><Entry x:Name="tyreComments" FontSize="Default" WidthRequest="180" HorizontalTextAlignment="Start"> <Entry.Behaviors> <Behaviors:ValidationBehavior PropertyName="Text"> <Behaviors:ValidationBehavior.Validators> <Validators:RequiredValidator /> <Validators:FormatValidator Message="" Format="" /> </Behaviors:ValidationBehavior.Validators> </Behaviors:ValidationBehavior> </Entry.Behaviors> </Entry></StackLayout> </StackLayout>

**Comment by ameerthehacker** [comment]
@Joeeyirelandd I believe I can understand your requirement. Just wrap the entry control in a stack layout and keep the remaining the same and it might work!

**Comment by ameerthehacker** [comment]
something like this
```xaml
<StackLayout Orientation="Horizontal" HorizontalOptions="Fill">
  <label
    x:Name="tyreLabel"
    Text="Tyres (and spare)"
    FontSize="Default"
    WidthRequest="180"
    Margin="10,10,10,10"
    HorizontalTextAlignment="Start"
  ></label>
  <Picker
    x:Name="tyrePicker"
    Title="Select Condition"
    Margin="0,0,30,0"
    HorizontalOptions="Center"
  >
    <Picker.ItemsSource>
      <x:Array Type="{x:Type x:String}">
        <x:String>Yes</x:String> <x:String>No</x:String>
        <x:String>N/A</x:String>
      </x:Array>
    </Picker.ItemsSource>
  </Picker>
  <StackLayout>
    <Entry
      x:Name="tyreComments"
      FontSize="Default"
      WidthRequest="180"
      HorizontalTextAlignment="Start"
    >
      <Entry.Behaviors>
        <Behaviors:ValidationBehavior PropertyName="Text">
          <Behaviors:ValidationBehavior.Validators>
            <Validators:RequiredValidator />
            <Validators:FormatValidator Message="" Format="" />
          </Behaviors:ValidationBehavior.Validators>
        </Behaviors:ValidationBehavior>
      </Entry.Behaviors>
    </Entry>
  </StackLayout>
</StackLayout>
```

**Comment by ameerthehacker** [comment]
Hope the above code helps, if you still need help please share the screenshot of what you get after doing this and what you actually expect!

**Comment by ColdstarJoey** [comment]
This worked for me but what it is doing now is moving my picker down as you can see if in this image:

[Screenshot](https://imgur.com/a/2DWrZ5C)

**Comment by ameerthehacker** [comment]
@Joeeyirelandd  Can you try changing the horizontal options of the parent to __Start__ rather than __Fill__
```xaml
<StackLayout Orientation="Horizontal"  HorizontalOptions="Start">
  ...
</StackLayout>
```

**Comment by ColdstarJoey** [comment]
The picker is still moving down after changing HorizontalOptions="Start"

**Comment by ameerthehacker** [comment]
Hey @Joeeyirelandd sorry for the confusion, try keeping the  HorizontalOptions="Fill" as you had and change the VerticalOptions="Start" or other options that might fix this!

**Comment by ColdstarJoey** [comment]
@ameerthehacker set it like this and the problem still occurs.
```
 <StackLayout Orientation="Horizontal" HorizontalOptions="Fill" VerticalOptions="Start">
...
</StackLayout>
```

**Comment by ameerthehacker** [comment]
@Joeeyirelandd try setting the __HeightRequest__ property to a constant value so that the new label that is getting attached does not make it weird

**Comment by ColdstarJoey** [comment]
@ameerthehacker is this on the Picker or Entry?

**Comment by ColdstarJoey** [comment]
With that on the side could I also use this method for a Picker so for example

`<Picker x:Name="pressureGaugesPicker" Title="Select Condition" Margin="0,0,30,0" HorizontalOptions="Center">
                    <Picker.ItemsSource>
                        <x:Array Type="{x:Type x:String}">
                            <x:String>Yes</x:String>
                            <x:String>No</x:String>
                            <x:String>N/A</x:String>
                        </x:Array>
                    </Picker.ItemsSource>
                    <Picker.Behaviors>
                        <Behaviors:ValidationBehavior PropertyName="Text">
                            <Behaviors:ValidationBehavior.Validators>
                                <Validators:RequiredValidator />
                                <Validators:FormatValidator Message="" Format="" />
                            </Behaviors:ValidationBehavior.Validators>
                        </Behaviors:ValidationBehavior>
                    </Picker.Behaviors>
                </Picker>`

Im guessing that would not work as its not text

**Comment by ColdstarJoey** [comment]
@ameerthehacker on the required field do you have the working so in a button clicked function if the required field is showing and the user presses submit then it shows an error?

**Comment by ameerthehacker** [comment]
> @ameerthehacker is this on the Picker or Entry?

This should be on the parent stack layout

**Comment by ameerthehacker** [comment]
> With that on the side could I also use this method for a Picker so for example
> 
> `<Picker x:Name="pressureGaugesPicker" Title="Select Condition" Margin="0,0,30,0" HorizontalOptions="Center"> <Picker.ItemsSource> <x:Array Type="{x:Type x:String}"> <x:String>Yes</x:String> <x:String>No</x:String> <x:String>N/A</x:String> </x:Array> </Picker.ItemsSource> <Picker.Behaviors> <Behaviors:ValidationBehavior PropertyName="Text"> <Behaviors:ValidationBehavior.Validators> <Validators:RequiredValidator /> <Validators:FormatValidator Message="" Format="" /> </Behaviors:ValidationBehavior.Validators> </Behaviors:ValidationBehavior> </Picker.Behaviors> </Picker>`
> 
> Im guessing that would not work as its not text

@Joeeyirelandd yes absolutely you can use this on picker but the __PropertyName__ attribute should be set to __SelectedItem__ something like this

```xaml
<Picker
  x:Name="pressureGaugesPicker"
  Title="Select Condition"
  Margin="0,0,30,0"
  HorizontalOptions="Center"
>
  <Picker.ItemsSource>
    <x:Array Type="{x:Type x:String}">
      <x:String>Yes</x:String> <x:String>No</x:String> <x:String>N/A</x:String>
    </x:Array>
  </Picker.ItemsSource>
  <Picker.Behaviors>
    <Behaviors:ValidationBehavior PropertyName="SelectedItem">
      <Behaviors:ValidationBehavior.Validators>
        <Validators:RequiredValidator />
        <Validators:FormatValidator Message="" Format="" />
      </Behaviors:ValidationBehavior.Validators>
    </Behaviors:ValidationBehavior>
  </Picker.Behaviors>
</Picker>
```

**Comment by ColdstarJoey** [comment]
The picker works but the same thing is happening with the stacklayout being in horizontal but i will change that, adding the start to the parent layout still does not stop it from pushing the picker down and not sure how to set the submit button up to check if they have been filled in

**Comment by ColdstarJoey** [comment]
@ameerthehacker if i add the validation to the picker it stops the picker from moving down anyway so that is sorted :D just the submit button function

**Comment by ameerthehacker** [comment]
@Joeeyirelandd that is easy to wire it up

Just add the ValidationGroupBehavior that I have talked to the root layout tag something like this

```xaml
<StackLayout>
  <!--
    This can be actually anything but should be a parent to all the controls
  -->
  <StackLayout.Behaviors>
    <Behaviors:ValidationGroupBehavior x:Name="form" />
  </StackLayout.Behaviors>
  <StackLayout Orientation="Horizontal" HorizontalOptions="Fill">
    <label
      x:Name="tyreLabel"
      Text="Tyres (and spare)"
      FontSize="Default"
      WidthRequest="180"
      Margin="10,10,10,10"
      HorizontalTextAlignment="Start"
    ></label>
    <!-- Add the group info to the control -->
    <Picker
      Group="{x:Reference form}"
      x:Name="pressureGaugesPicker"
      Title="Select Condition"
      Margin="0,0,30,0"
      HorizontalOptions="Center"
    >
      <Picker.ItemsSource>
        <x:Array Type="{x:Type x:String}">
          <x:String>Yes</x:String> <x:String>No</x:String>
          <x:String>N/A</x:String>
        </x:Array>
      </Picker.ItemsSource>
      <Picker.Behaviors>
        <Behaviors:ValidationBehavior PropertyName="SelectedItem">
          <Behaviors:ValidationBehavior.Validators>
            <Validators:RequiredValidator />
            <Validators:FormatValidator Message="" Format="" />
          </Behaviors:ValidationBehavior.Validators>
        </Behaviors:ValidationBehavior>
      </Picker.Behaviors>
    </Picker>
    <!-- Add the group info to the control -->
    <Entry
      Group="{x:Reference form}" 
      x:Name="tyreComments"
      FontSize="Default"
      WidthRequest="180"
      HorizontalTextAlignment="Start"
    >
      <Entry.Behaviors>
        <Behaviors:ValidationBehavior PropertyName="Text">
          <Behaviors:ValidationBehavior.Validators>
            <Validators:RequiredValidator />
            <Validators:FormatValidator Message="" Format="" />
          </Behaviors:ValidationBehavior.Validators>
        </Behaviors:ValidationBehavior>
      </Entry.Behaviors>
    </Entry>
  </StackLayout>
  ...
  <!--Here goes all the other controls you have-->
  ...
  <!-- Set the is enabled property of the submit button to validity of the form -->
  <Button Text="Submit" IsEnabled="{Binding Source={x:Reference form}, Path=IsValid}"/> 
</StackLayout>
```

**Comment by ColdstarJoey** [comment]
@ameerthehacker when adding the group code public ValidationGroupBehavior Group { get; set;} to the Validation Behavior.cs I get this error:

`Inconsistent accessibility: property type 'ValidationGroupBehavior' is less accessible than property 'ValidationBehavior.Group'`

**Comment by ameerthehacker** [comment]
@Joeeyirelandd can you please check whether you made the class ValidationGroupBehavior public

**Comment by ColdstarJoey** [comment]
`public class ValidationGroupBehavior : Behavior<View>` Sorry i made this change and that error is gone but now in the XAML it is `The Property 'Group was not found in type 'Entry'`

**Comment by ameerthehacker** [comment]
@Joeeyirelandd sorry my bad I made a small displacement. The group property should be on the validation behavior something like this

```xaml
<StackLayout>
  <!--
    This can be actually anything but should be parent to all the controls
  -->
  <StackLayout.Behaviors>
    <Behaviors:ValidationGroupBehavior x:Name="form" />
  </StackLayout.Behaviors>
  <StackLayout Orientation="Horizontal" HorizontalOptions="Fill">
    <label
      x:Name="tyreLabel"
      Text="Tyres (and spare)"
      FontSize="Default"
      WidthRequest="180"
      Margin="10,10,10,10"
      HorizontalTextAlignment="Start"
    ></label>
    <Picker
      x:Name="pressureGaugesPicker"
      Title="Select Condition"
      Margin="0,0,30,0"
      HorizontalOptions="Center"
    >
      <Picker.ItemsSource>
        <x:Array Type="{x:Type x:String}">
          <x:String>Yes</x:String> <x:String>No</x:String>
          <x:String>N/A</x:String>
        </x:Array>
      </Picker.ItemsSource>
      <Picker.Behaviors>
        <!-- Add the group info to the behavior -->
        <Behaviors:ValidationBehavior Group="{x:Reference form}" PropertyName="SelectedItem">
          <Behaviors:ValidationBehavior.Validators>
            <Validators:RequiredValidator />
            <Validators:FormatValidator Message="" Format="" />
          </Behaviors:ValidationBehavior.Validators>
        </Behaviors:ValidationBehavior>
      </Picker.Behaviors>
    </Picker>
    <Entry
      x:Name="tyreComments"
      FontSize="Default"
      WidthRequest="180"
      HorizontalTextAlignment="Start"
    >
      <Entry.Behaviors>
       <!-- Add the group info to the behavior -->
        <Behaviors:ValidationBehavior Group="{x:Reference form}" PropertyName="Text">
          <Behaviors:ValidationBehavior.Validators>
            <Validators:RequiredValidator />
            <Validators:FormatValidator Message="" Format="" />
          </Behaviors:ValidationBehavior.Validators>
        </Behaviors:ValidationBehavior>
      </Entry.Behaviors>
    </Entry>
  </StackLayout>
  ...
  <!--Here goes all the other controls you have-->
  ...
  <!-- Set the is enabled property of the submit button to validity of the form -->
  <Button Text="Submit" IsEnabled="{Binding Source={x:Reference form}, Path=IsValid}"/> 
</StackLayout>
```

**Comment by ColdstarJoey** [comment]
Working Like a charm now thank you

**Comment by ameerthehacker** [comment]
@Joeeyirelandd happy to help. If you liked this pattern give me some claps on my [medium article](https://medium.com/@ameerjhanprof/declarative-xamarin-form-validation-c174d2a74618) share it with your friends and star the repo

**Comment by ColdstarJoey** [comment]
when adding this code to the xaml 

`<Validators:RequiredValidator />
<Validators:FormatValidator Message="" Format="" />`

it always makes 2 errors which are 

A value of type 'RequiredValidator' cannot be added to a collection or dictionary of type 'ObservableCollection'.	

AND

A value of type 'FormatValidator' cannot be added to a collection or dictionary of type 'ObservableCollection'.	

but I can still run the app

**Comment by ameerthehacker** [comment]
@Joeeyirelandd those warnings are kind of bug in the visual studio which is statically cannot say that RequiredValidator is implementing IValidator by analyzing the xaml. Nothing to be worried about!
